// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250925153945_ajustesbanco")]
    partial class ajustesbanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Models.CriarUsuario", b =>
                {
                    b.Property<int>("Iduser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Iduser");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("backend.Models.RegistrarHorario", b =>
                {
                    b.Property<int>("Idregistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Iduser")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSemana")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistroEntrada")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("RegistroSaida")
                        .HasColumnType("datetime");

                    b.HasKey("Idregistro");

                    b.ToTable("RegistroHorarios");
                });
#pragma warning restore 612, 618
        }
    }
}
